version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    volumes:
      - ./data:/var/lib/postgresql/data